### PR TITLE
Fix docs link in src/index.ts:86

### LINKED ISSUE #555: Code points to a non-existing doc URL
https://github.com/octokit/plugin-throttling.js/blob/4d53e03bc43ccd5ad3f1cd9465838467e9d472da/src/index.ts#L86

Try out the link directly here: https://github.com/octokit/rest.js#throttling

### PR DESCRIPTION
**Pull request by kfcampbell**
Fixes #555. 

The docs URL for octokit/rest.js has changed since implementation here.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -83,7 +83,7 @@ export function throttling(octokit: Octokit, octokitOptions: OctokitOptions) {
   ) {
     throw new Error(`octokit/plugin-throttling error:
         You must pass the onSecondaryRateLimit and onRateLimit error handlers.
-        See https://github.com/octokit/rest.js#throttling
+        See https://octokit.github.io/rest.js/v19#throttling
```
Comment (wolfy1339) [inline src/index.ts:86]: Let's not hardcode a version. The website redirects to the latest version by default
```suggestion
        See https://octokit.github.io/rest.js/#throttling
```

Comment (kfcampbell) [reply src/index.ts:86]: Great catch!

**Review by wolfy1339 — APPROVED** [review]
