### PR TITLE
fix(types): improvements to internal types and `options` parameter

### LINKED ISSUE #641: LimitHandler typing uses type `object` for options
Relevant line: https://github.com/octokit/plugin-throttling.js/blob/main/src/types.ts#L6

The `object` type is not readable, even though the examples show doing things like "options.method" or "options.url", but with Typescript, none of this works:

2023-11-02 19_02_38-Window

tsconfig.json:
```json
{
  "compilerOptions": {
    "strict": true,
    "jsx": "react-jsx",
    "jsxImportSource": "react",
    "allowSyntheticDefaultImports": true,
    "noErrorTruncation": true
  }
}
```

And relevant package versions:
```
    "@octokit/auth-token": "^4.0.0",
    "@octokit/plugin-throttling": "^8.1.2",
    "@octokit/rest": "^20.0.2",
```

### PR DESCRIPTION
**Pull request by wolfy1339**
Fixes #641

This should unblock users, as using `object` doesn't allow users to access options properties in TypeScript.

The types were inferred from the call to `octokit.hook.wrap()`, and also confirmed from the types from`@octokit/core`

https://github.com/octokit/core.js/blob/1c64ce28a2352c88091732985502b257cb242c02/src/types.ts#L55-L59

### CODE REVIEW

**Review by gr2m — DISMISSED** [review]
cheers!

**Comment by gr2m** [comment]
@octokit/maintainers you can remove the required CI from all @octokit repositories using this @octoherd script: https://github.com/octoherd/script-remove-required-ci-check

**Comment by wolfy1339** [comment]
Waiting on https://github.com/octokit/types.ts/pull/594

**Comment by wolfy1339** [comment]
@oscard0m Could you review this to make sure it all makes sense

----

The types for the handler were taken from `@octokit/core`
 https://github.com/octokit/core.js/blob/1c64ce28a2352c88091732985502b257cb242c02/src/types.ts#L55-L58

**Comment by oscard0m** [comment]
> @oscard0m Could you review this to make sure it all makes sense
> 
> The types for the handler were taken from `@octokit/core` https://github.com/octokit/core.js/blob/1c64ce28a2352c88091732985502b257cb242c02/src/types.ts#L55-L59

I won’t be available until next week to review this. Is that ok?

**Comment by wolfy1339** [comment]
That's fine

File: src/index.ts [hunk 1]
```diff
@@ -100,9 +110,12 @@ export function throttling(octokit: Octokit, octokitOptions: OctokitOptions) {
     octokit.log.warn("Error in throttling-plugin limit handler", e),
   );
 
-  // @ts-expect-error
   state.retryLimiter.on("failed", async function (error, info) {
-    const [state, request, options] = info.args;
+    const [state, request, options] = info.args as [
+      State,
+      OctokitResponse<any>,
```
Comment (oscard0m) [inline src/index.ts:116]: Would it be less intrusive to use this:

```suggestion
      OctokitResponse<any> & { retryCount: number },
```

Instead of re-declaring module `@octokit/types`? Or is there an issue you were facing I'm not seeing?

File: test/exports.test.ts [hunk 2]
```diff
@@ -10,7 +10,9 @@ describe("Exports", function () {
     };
 
     options.enabled = false;
+    // @ts-expect-error
     options.onRateLimit(10, {}, {} as Octokit, 0);
+    // @ts-expect-error
     options.onSecondaryRateLimit(10, {}, {} as Octokit, 0);
   });
```
Comment (oscard0m) [inline test/exports.test.ts:17]: Should we pass more significant `request` objects as a second argument instead of adding `// @ts-expect-error` as part of this PR?

File: src/wrap-request.ts [hunk 3]
```diff
@@ -1,17 +1,31 @@
...
+    options: Required<EndpointDefaults>,
+  ) => OctokitResponse<any> | Promise<OctokitResponse<any>>,
+  options: Required<EndpointDefaults>,
+) {
   const isWrite = options.method !== "GET" && options.method !== "HEAD";
   const { pathname } = new URL(options.url, "http://github.test");
   const isSearch = options.method === "GET" && pathname.startsWith("/search/");
   const isGraphQL = pathname.startsWith("/graphql");
 
+  // @ts-expect-errors
```
Comment (oscard0m) [inline src/wrap-request.ts:28]: Can this TS error be solved with the same approach used in `types.ts` (see also my comment there)?

**Review by oscard0m — APPROVED** [review]
LGTM overall. Great job as always @wolfy1339 

I left some comments on some `@ts-expect-error`, just in case there is a chance we can solve them.

File: src/index.ts (hunk 1 above)
Comment (wolfy1339) [reply src/index.ts:116]: Since the module adds a property to the request, we need to augment the types with that property so it's available to end users when they use this plugin.

File: test/exports.test.ts (hunk 2 above)
Comment (wolfy1339) [reply test/exports.test.ts:17]: I don't think we need to here. This only tests that the method is available and exported.

The other tests handle it's proper usage

File: src/wrap-request.ts (hunk 3 above)
Comment (wolfy1339) [reply src/wrap-request.ts:28]: I'll have to look into it, but I'm not sure I found a way to fix it.

It just caused more errors without it

Comment (wolfy1339) [reply src/wrap-request.ts]: I managed to remove some more, including this one. And added an explanation comment

**Comment by wolfy1339** [comment]
This is odd... The typescript compiler doesn't complain when compiling the whole project for the types, it only complains for the `validate:ts` task

**Comment by tarebyte** [comment]
> @octokit/maintainers you can remove the required CI from all

I'm on this team, but I'm not an org admin. Sorry!

**Comment by wolfy1339** [comment]
This seems to do with the fact that typescript is compiling the files one by one, and not taking them into account as to how they affect other files.

When we build as a project, it keeps this context when it compiles all the files

**Review by oscard0m — APPROVED** [review]

**Comment by wolfy1339** [comment]
Well this is annoying.... Merging in `main` dismissed the review

**Review by oscard0m — APPROVED** [review]
