### PR TITLE
fix: don't deadlock on 10+ concurrent requests needing auth

### LINKED ISSUE #754: global group can deadlock requests if auth is not already cached
When running Octokit with auth, and trying to concurrently perform 10+ operations, a deadlock will happen. 
The reason: https://github.com/octokit/plugin-throttling.js/blob/main/src/index.ts#L30
10 concurrent in global. If this buffer is filled with 10 requests, and no auth token is present, the auth request will end up as number 11, and never run, again causing the 10 requests in the queue to wait forever. 

Example code to reproduce: 
```
const octokit = await (new App({
  appId,
  privateKey,
  Octokit: Octokit.defaults({
    baseUrl,
  }),
})).getInstallationOctokit(installationId);

const artifacts = [
  'test-1',
  'test-2',
  'test-3',
  'test-4',
  'test-5',
  'test-6',
  'test-7',
  'test-8',
  'test-9',
  'test-10'
];

//await fetchLastSuccessfulDeployment('fis', 'ban', 'Finn', 'horizontal');
await Promise.all(
  artifacts.map(async (artifact) => {
    return await await octokit.rest.actions.listWorkflowRuns({
      owner: 'owner',
      repo: 'repo',
      workflow_id: `deploy.${artifact}.yaml`,
    });
  })
);
```
This will hang forever.

By reducing the array to 9 elements, it works. 
By awaiting a single request before looping, it works (remove the comment before the loop, this will get a token and cache it).
By changing maxConcurrent to 11, it works. 

I think it would be a good idea to let auth requests have its own queue, and not end up in the global one.

### PR DESCRIPTION
**Pull request by jenseng**
Fixes #754 
Fixes octokit/octokit.js#2800

Give auth requests a dedicated queue. This ensures that they don't cause a deadlock when 10+ concurrent requests are made that need authentication (i.e. either we've never authed, or the token has expired).

### CODE REVIEW

**Comment by wolfy1339** [comment]
Can you update the PR with https://github.com/octokit/auth-app.js/pull/689

**Comment by jenseng** [comment]
> Can you update the PR with [octokit/auth-app.js#689](https://github.com/octokit/auth-app.js/pull/689)

Done! I only updated the dev dependency and the test, since it can still work with older versions (just suboptimally). Let me know if we should tweak peerDependencies/etc too

File: src/wrap-request.ts [hunk 1]
```diff
@@ -20,8 +20,13 @@ async function doRequest(
   ) => Promise<OctokitResponse<any>>) & { retryCount: number },
   options: Required<EndpointDefaults>,
 ) {
-  const isWrite = options.method !== "GET" && options.method !== "HEAD";
   const { pathname } = new URL(options.url, "http://github.test");
+  const isAuth =
+    options.method === "POST" &&
+    (pathname === "/login/oauth/access_token" ||
+      /^\/app\/installations\/[^/]+\/access_tokens$/.test(pathname));
```
Comment (wolfy1339) [inline src/wrap-request.ts:27]: Does this handle all methods of authentication?

Comment (jenseng) [reply src/wrap-request.ts:27]: from the standpoint of octokit auth strategies it should, from what i've been able to glean from the GitHub docs, [the octokit docs](https://actions-cool.github.io/octokit-rest/guide/01_authentication/), and the octokit codebases 🤞:
- PATs ([`@octokit/auth-token`](https://github.com/octokit/auth-token.js)) are provided directly, there is no API call to retrieve one.
- OAuth Apps ([`@octokit/auth-oauth-app`](https://github.com/octokit/auth-oauth-app.js)) retrieve their tokens [via `/login/oauth/access_token`](https://github.com/octokit/oauth-methods.js/blob/fefd410255423000e555a4698776cf6034cf7f70/src/refresh-token.ts#L32)
- GitHub Apps ([`@octokit/auth-app`](https://github.com/octokit/auth-app.js/)) retrieve their tokens [via `/app/installations/.../access_tokens`](https://github.com/octokit/auth-app.js/blob/76398ebbac5e9e780caccd6c6ba7393f27793e23/src/get-installation-authentication.ts#L136)
- GitHub Actions ([`@octokit/auth-action`](https://github.com/octokit/auth-action.js) pull the token [from the environment variables](http://github.com/octokit/auth-action.js/blob/fecc61ee5635a77e3013b3407e62873249f0c7b1/src/index.ts#L25-L45) 

that said, there are other endpoints which could be considered authentication-y, so we could expand this to cover them, wdyt? for example:
- [reset an oauth token](https://docs.github.com/en/rest/apps/oauth-applications?apiVersion=2022-11-28#reset-a-token)
- [create a scoped access token](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-a-scoped-access-token)

Comment (wolfy1339) [reply src/wrap-request.ts:27]: I think handling both of those additional endpoints is fine.

**Review by wolfy1339 — APPROVED** [review]

**Comment by gr2m** [comment]
Great work on adding custom throttling for auth requests 🚀
